// List<Map<String , dynamic>>

Map<String, dynamic> registrationData = {
  "code": "200",
  "message": "Success",
  "data": [
    {
      "stud_name": "علي محمد",
      "date_of_birth": "2005-06-15",
      "place_of_birth": "القاهرة",
      "currentplace_residence": "الجيزة",
      "area": "الهرم",
      "disease": "لا يوجد",
      "school": "مدرسة الأهرام",
      "ratio": "95%",
      "classes": "ثانوية عامة",
      "skills": "برمجة, تصميم",
      "fav_school": "مدرسة المستقبل",
      "participations": "مسابقة العلوم, دوري كرة القدم",
      "future_ambitions": "طبيب",
      "join_school": "2020",
      "guardian_name": "أحمد محمد",
      "relationship": "أب",
      "profession": "مهندس",
      "guardian_phone": "01234567890",
      "phone": "09876543210",
      "whatsapp": "09876543210"
    },
    {
      "stud_name": "فاطمة علي",
      "date_of_birth": "2006-03-22",
      "place_of_birth": "الإسكندرية",
      "currentplace_residence": "الإسكندرية",
      "area": "وسط المدينة",
      "disease": "لا يوجد",
      "school": "مدرسة النيل",
      "ratio": "90%",
      "classes": "ثانوية عامة",
      "skills": "رسم, موسيقى",
      "fav_school": "مدرسة الإبداع",
      "participations": "مسابقة الرسم, الكورال",
      "future_ambitions": "فنانة",
      "join_school": "2021",
      "guardian_name": "سعاد علي",
      "relationship": "أم",
      "profession": "معلمة",
      "guardian_phone": "01234567891",
      "phone": "09876543211",
      "whatsapp": "09876543211"
    },
    {
      "stud_name": "أحمد سعيد",
      "date_of_birth": "2004-08-10",
      "place_of_birth": "المنصورة",
      "currentplace_residence": "المنصورة",
      "area": "حي الجامعة",
      "disease": "لا يوجد",
      "school": "مدرسة المنصورة",
      "ratio": "92%",
      "classes": "ثانوية عامة",
      "skills": "رياضيات, كرة سلة",
      "fav_school": "مدرسة النور",
      "participations": "بطولة السلة, مسابقة الرياضيات",
      "future_ambitions": "مهندس",
      "join_school": "2019",
      "guardian_name": "محمد سعيد",
      "relationship": "أب",
      "profession": "طبيب",
      "guardian_phone": "01234567892",
      "phone": "09876543212",
      "whatsapp": "09876543212"
    },
    {
      "stud_name": "سارة خالد",
      "date_of_birth": "2005-11-30",
      "place_of_birth": "دمياط",
      "currentplace_residence": "دمياط",
      "area": "وسط المدينة",
      "disease": "لا يوجد",
      "school": "مدرسة الأمل",
      "ratio": "88%",
      "classes": "ثانوية عامة",
      "skills": "تكنولوجيا المعلومات, كتابة",
      "fav_school": "مدرسة القمة",
      "participations": "مسابقة التكنولوجيا, مهرجان الكتاب",
      "future_ambitions": "كاتبة",
      "join_school": "2020",
      "guardian_name": "علي خالد",
      "relationship": "أب",
      "profession": "محامي",
      "guardian_phone": "01234567893",
      "phone": "09876543213",
      "whatsapp": "09876543213"
    },
    {
      "stud_name": "محمد رضا",
      "date_of_birth": "2006-05-05",
      "place_of_birth": "الأقصر",
      "currentplace_residence": "الأقصر",
      "area": "حي العوامية",
      "disease": "لا يوجد",
      "school": "مدرسة الأقصر",
      "ratio": "85%",
      "classes": "ثانوية عامة",
      "skills": "رياضة, رسم",
      "fav_school": "مدرسة الفنون",
      "participations": "بطولة كرة القدم, معرض الرسم",
      "future_ambitions": "فنان",
      "join_school": "2021",
      "guardian_name": "يوسف رضا",
      "relationship": "أب",
      "profession": "فنان",
      "guardian_phone": "01234567894",
      "phone": "09876543214",
      "whatsapp": "09876543214"
    },
    {
      "stud_name": "نور أيمن",
      "date_of_birth": "2007-01-12",
      "place_of_birth": "السويس",
      "currentplace_residence": "السويس",
      "area": "حي العبور",
      "disease": "لا يوجد",
      "school": "مدرسة السويس",
      "ratio": "93%",
      "classes": "ثانوية عامة",
      "skills": "موسيقى, رياضة",
      "fav_school": "مدرسة الإبداع",
      "participations": "فرقة المدرسة الموسيقية, دوري رياضي",
      "future_ambitions": "موسيقية",
      "join_school": "2020",
      "guardian_name": "علي أيمن",
      "relationship": "أب",
      "profession": "محاسب",
      "guardian_phone": "01234567895",
      "phone": "09876543215",
      "whatsapp": "09876543215"
    },
    {
      "stud_name": "ليلى حسين",
      "date_of_birth": "2005-07-25",
      "place_of_birth": "بورسعيد",
      "currentplace_residence": "بورسعيد",
      "area": "حي الشرق",
      "disease": "لا يوجد",
      "school": "مدرسة بورسعيد",
      "ratio": "91%",
      "classes": "ثانوية عامة",
      "skills": "كتابة, لغات",
      "fav_school": "مدرسة اللغات",
      "participations": "مسابقة الكتابة, مسابقة اللغات",
      "future_ambitions": "مترجمة",
      "join_school": "2019",
      "guardian_name": "أحمد حسين",
      "relationship": "أب",
      "profession": "مستشار قانوني",
      "guardian_phone": "01234567896",
      "phone": "09876543216",
      "whatsapp": "09876543216"
    }
  ]
};
